---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  RepositoryName:
    Type: String
    Description: Name of the CodeCommit repository
Resources:
  MyCodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: mexyRepo